CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS images (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, path TEXT UNIQUE, mp4 TEXT UNIQUE, webm TEXT UNIQUE, pending INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS ratings (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, uid INTEGER, iid INTEGER, passed BOOLEAN, at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
